name: nhost_flutter_auth
description: >
  Provides Nhost authentication state to your Flutter app, making it easy to set
  up protected resources, and react to sign ins and sign outs.
version: 4.1.0
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_flutter_auth
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  http_parser: ^4.0.2
  http: ^1.1.2
  logging: ^1.2.0
  meta: ^1.10.0
  path: ^1.8.0

  #Nhost_dart
  nhost_sdk: ^5.0.0
  nhost_auth_dart: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: any
  mockito: ^5.4.4
